# Site settings
title: Aziz Punjani
email: aziz.punjani@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.azizpunjani.com" # the base hostname & protocol for your site
twitter_username: azizpunjani
github_username:  azizpunjani
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
